from kata.agent_bundle import AGENT_ENTRY_FILENAME, AGENT_MANIFEST_FILENAME

SUBMISSIONS_DIRNAME = "submissions"
SUBMISSION_SCHEMA_VERSION = 2
SUBMISSION_METADATA_FILENAME = "submission.json"
SUBMISSION_AGENT_FILENAME = AGENT_ENTRY_FILENAME
SUBMISSION_AGENT_MANIFEST_FILENAME = AGENT_MANIFEST_FILENAME
TOP_LEVEL_SUBMISSION_FILENAMES = {
    SUBMISSION_METADATA_FILENAME,
    SUBMISSION_AGENT_FILENAME,
    SUBMISSION_AGENT_MANIFEST_FILENAME,
}
SUPPORTED_SUBMISSION_MODES = {"miner"}
DEFAULT_AGENT_PLACEHOLDER = (
    "Replace this scaffold with a real challenger agent implementation before opening a PR."
)
SUBMISSION_ID_CONVENTION = "<github-username>-YYYYMMDD-NN"

PR_ACTION_CLOSE_INVALID = "close-invalid"
PR_ACTION_EVALUATE = "evaluate"
PR_ACTION_CLOSE_LOSING = "close-losing"
PR_ACTION_RERUN_STALE = "rerun-stale"
PR_ACTION_MERGE = "merge"
